"""
Altium PCB object class record.

Parse class definitions from `Classes6/Data`.

Despite the historical class name `AltiumPcbNetClass`, this stream stores
multiple PCB object-class families: net classes, component classes, pad
classes, layer classes, differential-pair classes, polygon classes, and
from-to classes.
"""

import logging
from dataclasses import dataclass, field
from typing import Any

from .altium_pcb_enums import PcbNetClassKind

log = logging.getLogger(__name__)


def _new_class_record_template() -> dict[str, Any]:
    """
    Key set Altium writes for a `Classes6/Data` record, in its own order.

    Used only when serializing a class that was constructed in code rather
    than parsed from a file, so a new class carries the same fields as the
    ones Altium authored beside it. `M0..Mn` are inserted where the member
    keys belong; `NAME`, `KIND` and `UNIQUEID` are overwritten by the caller.
    """
    return {
        'SELECTION': 'FALSE',
        'LAYER': 'MULTILAYER',
        'LOCKED': 'FALSE',
        'POLYGONOUTLINE': 'FALSE',
        'USERROUTED': 'TRUE',
        'KEEPOUT': 'FALSE',
        'UNIONINDEX': '0',
        'NAME': '',
        'KIND': '0',
        'SUPERCLASS': 'FALSE',
        'M0': '',
        'SELECTED': 'FALSE',
        'SCHAUTOGENERATEDCLUSTER': 'FALSE',
        'UNIQUEID': '',
    }


@dataclass
class AltiumPcbNetClass:
    """
    PCB object class definition from `Classes6/Data`.
    
    PCB object classes group objects (nets, components, pads, layers,
    differential pairs, polygons, etc.)
    together for design rule application and organization.
    
    Attributes:
        name: Class name (e.g., "All Nets", "Power Nets", "Signal Nets")
        kind: Class type (0=Net, 1=Component, 2=From-To, 3=Pad, 4=Layer, 6=Diff Pair, 7=Polygon)
        member_count: Number of members in this class
        members: List of member names/IDs
        enabled: Is class enabled
        unique_id: Unique identifier
    
        _raw_record: Complete raw record dict
    
        # Access properties
        print(f"Class: {net_class.name} (Kind: {net_class.kind.name})")
        print(f"Members: {net_class.member_count}")
    
        # Serialize back
        record = net_class.to_record()
    """

    # Core properties
    name: str = ""
    kind: PcbNetClassKind = PcbNetClassKind.NET
    member_count: int = 0
    members: list[str] = field(default_factory=list)

    # Properties
    enabled: bool = True
    unique_id: str = ""

    # Raw record
    _raw_record: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_record(cls, record: dict[str, Any]) -> 'AltiumPcbNetClass':
        """
        Parse net class from Classes6/Data text record.
        
        Args:
            record: Text record dict from get_records_in_section()
        
        Returns:
            AltiumPcbNetClass instance
        """
        net_class = cls(_raw_record=record.copy())

        # Parse basic properties
        net_class.name = record.get('NAME', '')

        # Parse kind
        try:
            kind_val = int(record.get('KIND', 0))
            net_class.kind = PcbNetClassKind(kind_val)
        except (ValueError, KeyError):
            net_class.kind = PcbNetClassKind.NET

        # Parse members (M0, M1, M2, ...)
        members = []
        i = 0
        while f'M{i}' in record:
            member = record[f'M{i}']
            members.append(member)
            i += 1
        net_class.members = members

        # Parse member count. Altium often omits MEMBERCOUNT even when M0, M1,
        # ... member keys are present, so derive the public count from members
        # when no explicit count exists.
        if 'MEMBERCOUNT' in record:
            try:
                net_class.member_count = int(record.get('MEMBERCOUNT', 0))
            except ValueError:
                net_class.member_count = 0
        else:
            net_class.member_count = len(members)

        # Parse properties
        net_class.enabled = record.get('ENABLED', 'TRUE') == 'TRUE'
        net_class.unique_id = record.get('UNIQUEID', '')

        return net_class

    def to_record(self) -> dict[str, Any]:
        """
        Serialize net class to Classes6/Data text record format.

        The member keys `M0..Mn` are rebuilt from scratch rather than updated
        in place, so shrinking `members` drops the surplus keys instead of
        leaving stale ones behind. They are re-emitted at the position the
        source record used, keeping an untouched class byte-identical.

        `MEMBERCOUNT` and `ENABLED` are only written when the source record
        carried them: Altium omits both when writing `Classes6/Data`, and
        introducing keys it did not write is not a faithful round trip.

        Returns:
            Text record dict
        """
        raw = self._raw_record or _new_class_record_template()
        member_keys = [
            key for key in raw
            if key.startswith('M') and key[1:].isdigit()
        ]

        record: dict[str, Any] = {}
        members_emitted = False
        for key, value in raw.items():
            if key in member_keys:
                if not members_emitted:
                    for i, member in enumerate(self.members):
                        record[f'M{i}'] = member
                    members_emitted = True
                continue
            record[key] = value
        if not members_emitted:
            for i, member in enumerate(self.members):
                record[f'M{i}'] = member

        # Update basic properties
        record['NAME'] = self.name
        record['KIND'] = str(int(self.kind))
        if 'MEMBERCOUNT' in raw:
            member_count = len(self.members) if self.members else self.member_count
            record['MEMBERCOUNT'] = str(member_count)

        # Update properties
        if 'ENABLED' in raw:
            record['ENABLED'] = 'TRUE' if self.enabled else 'FALSE'
        if self.unique_id:
            record['UNIQUEID'] = self.unique_id

        return record

    def __repr__(self) -> str:
        """
        String representation.
        """
        try:
            kind_name = self.kind.name
        except ValueError:
            kind_name = str(int(self.kind))

        return (f"AltiumPcbNetClass(name='{self.name}', kind={kind_name}, "
                f"members={self.member_count})")
